import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import {HeroParallaxDemo} from "./components/Parallax";
import "./globals.css";

// Importing and setting up fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <div className='relative w-full flex item-center justify-center'></div>
          <Navbar />
          <HeroParallaxDemo />
        </div>
        {children}
      </body>
    </html>
  );
}
